layout_spectrum: 0.13598859356716275
typography_spectrum: 0.9331371025182307
color:
  brandStrength: 0.4792387324851006
  lightness: 0.8238850987982005
  saturation: 0.7433618151117116
  rhythmicContrast: 0.7760952617973089
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
name: shawntan.sg
navigation:
  - name: About Me
    id: 5f6f0021-ed1d-4483-b2b3-529f396c8e77
    type: content
title: Shawn Tan
description: Your International Property Consultant
