typography_spectrum: 0.9955848718527704
color:
  brandStrength: 0.3213977252598852
  lightness: 0.04151219385676086
  saturation: 0.40385872311890125
  rhythmicContrast: 0.5057183930184692
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.38181331427767873
name: shawntan.sg
navigation:
  - name: About Me
    id: 5f6f0021-ed1d-4483-b2b3-529f396c8e77
    type: content
title: Shawn Tan
description: Your International Property Consultant
